# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [329]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [330]:
# Create a 1-dimensional NumPy array using np.array()
arr_1d = np.array([2,4,-5,3])

# Create a 2-dimensional NumPy array using np.array()
arr_2d = np.array([[1, 2], [3, 4]])


# Create a 3-dimensional Numpy array using np.array()
arr_3d =  np.array([[[1, 2], [-1, 4]], [[4,-1], [7, 8]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [331]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(arr_1d.shape)
print(arr_1d.ndim)
print(arr_1d.dtype)
print(arr_1d.size)
print(type(arr_1d))

(4,)
1
int32
4
<class 'numpy.ndarray'>


In [332]:
# Attributes of 2-dimensional array
print(arr_2d.shape)
print(arr_2d.ndim)
print(arr_2d.dtype)
print(arr_2d.size)
print(type(arr_2d))

(2, 2)
2
int32
4
<class 'numpy.ndarray'>


In [333]:
# Attributes of 3-dimensional array
print(arr_3d.shape)
print(arr_3d.ndim)
print(arr_3d.dtype)
print(arr_3d.size)
print(type(arr_3d))

(2, 2, 2)
3
int32
8
<class 'numpy.ndarray'>


In [334]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
arr_df = pd.DataFrame(arr_2d)
print(arr_df)

   0  1
0  1  2
1  3  4


In [335]:
# Create an array of shape (10, 2) with only ones
arr4 = np.ones((10,2))
print(arr4)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [336]:
# Create an array of shape (7, 2, 3) of only zeros
arr5 = np.zeros((7,2,3))
print(arr5)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [337]:
# Create an array within a range of 0 and 100 with step 3
arr6 = np.arange(0, 100, 3)
print(arr6)


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [338]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr7 = np.random.rand(7, 2) * 10
print(arr7)

[[8.16385735 9.67973765]
 [0.88408223 7.91817839]
 [5.89955897 4.80045967]
 [4.20535779 7.84668264]
 [6.39361357 8.05044668]
 [9.03151059 6.17263712]
 [9.80462725 6.0808785 ]]


In [339]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr8 = np.random.rand(3, 5) * 1
print(arr8)

[[0.63664432 0.55481561 0.09100209 0.72639703 0.54744631]
 [0.45091045 0.91047128 0.29795945 0.52360228 0.69764187]
 [0.79647178 0.45934681 0.84209142 0.76891774 0.06623598]]


In [340]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr8 = np.random.rand(4, 6) * 10
print(arr8)

[[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864  1.5599452 ]
 [0.58083612 8.66176146 6.01115012 7.08072578 0.20584494 9.69909852]
 [8.32442641 2.12339111 1.81824967 1.8340451  3.04242243 5.24756432]
 [4.31945019 2.9122914  6.11852895 1.39493861 2.92144649 3.66361843]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [341]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr9 = np.random.randint(1, 10, size=(3, 7))
print(arr9)

# Find the unique numbers in the array you just created
unique_nums = np.unique(arr9)
print('unique nums are:' , unique_nums)


[[3 7 4 9 3 5 3]
 [7 5 9 7 2 4 9]
 [2 9 5 2 4 7 8]]
unique nums are: [2 3 4 5 7 8 9]


In [342]:
# Find the 0'th index of the latest array you created
print(arr9[0])

[3 7 4 9 3 5 3]


In [343]:
# Get the first 2 rows of latest array you created
print(arr9[0:2])

[[3 7 4 9 3 5 3]
 [7 5 9 7 2 4 9]]


In [344]:
# Get the first 2 values of the first 2 rows of the latest array
print(arr9[0:2,0:2])

[[3 7]
 [7 5]]


In [345]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr10 = np.random.rand(3, 5) * 10
arr11 = np.ones((3,5))
print(arr10,arr11)

[[0.34388521 9.09320402 2.58779982 6.62522284 3.11711076]
 [5.20068021 5.46710279 1.84854456 9.69584628 7.75132823]
 [9.39498942 8.9482735  5.97899979 9.21874235 0.88492502]] [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [346]:
# Add the two arrays together
arr12 = arr10 + arr11
print(arr12)

[[ 1.34388521 10.09320402  3.58779982  7.62522284  4.11711076]
 [ 6.20068021  6.46710279  2.84854456 10.69584628  8.75132823]
 [10.39498942  9.9482735   6.97899979 10.21874235  1.88492502]]


In [347]:
# Create another array of ones of shape (5, 3)
arr13 = np.random.rand(5, 3) * 10
print(arr13)

[[1.95982862 0.45227289 3.25330331]
 [3.8867729  2.71349032 8.28737509]
 [3.56753327 2.8093451  5.42696083]
 [1.40924225 8.02196981 0.74550644]
 [9.86886937 7.72244769 1.98715682]]


In [348]:
# Try add the array of ones and the other most recent array together
arr14 = arr13 + arr12

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [349]:
# Create another array of ones of shape (3, 5)
arr15 = np.ones((3,5))


In [350]:
# Subtract the new array of ones from the other most recent array
arr13 = arr13.reshape(3,5)
arr16 = arr13 - arr15
print(arr16)

[[ 0.95982862 -0.54772711  2.25330331  2.8867729   1.71349032]
 [ 7.28737509  2.56753327  1.8093451   4.42696083  0.40924225]
 [ 7.02196981 -0.25449356  8.86886937  6.72244769  0.98715682]]


In [351]:
# Multiply the ones array with the latest array
arr17 = arr16 * arr15
print(arr17)

[[ 0.95982862 -0.54772711  2.25330331  2.8867729   1.71349032]
 [ 7.28737509  2.56753327  1.8093451   4.42696083  0.40924225]
 [ 7.02196981 -0.25449356  8.86886937  6.72244769  0.98715682]]


In [352]:
# Take the latest array to the power of 2 using '**'
arr18=arr17**2
print(arr18)

[[9.21270988e-01 3.00004988e-01 5.07737580e+00 8.33345776e+00
  2.93604907e+00]
 [5.31058357e+01 6.59222708e+00 3.27372968e+00 1.95979822e+01
  1.67479219e-01]
 [4.93080600e+01 6.47669737e-02 7.86568438e+01 4.51913030e+01
  9.74478578e-01]]


In [353]:
# Do the same thing with np.square()
arr19 = np.square(arr17)
print(arr19)

[[9.21270988e-01 3.00004988e-01 5.07737580e+00 8.33345776e+00
  2.93604907e+00]
 [5.31058357e+01 6.59222708e+00 3.27372968e+00 1.95979822e+01
  1.67479219e-01]
 [4.93080600e+01 6.47669737e-02 7.86568438e+01 4.51913030e+01
  9.74478578e-01]]


In [354]:
# Find the mean of the latest array using np.mean()
print(np.mean(arr19))

18.300057656614815


In [355]:
# Find the maximum of the latest array using np.max()
print(np.max(arr19))

78.656843831265


In [356]:
# Find the minimum of the latest array using np.min()
print(np.min(arr19))

0.06476697371139888


In [357]:
# Find the standard deviation of the latest array
print(np.std(arr19))

24.496678378416078


In [358]:
# Find the variance of the latest array
print(np.var(arr19))

600.0872515755577


In [359]:
# Reshape the latest array to (3, 5, 1)
arr20 = arr19.reshape(3, 5, 1)
print(arr20)

[[[9.21270988e-01]
  [3.00004988e-01]
  [5.07737580e+00]
  [8.33345776e+00]
  [2.93604907e+00]]

 [[5.31058357e+01]
  [6.59222708e+00]
  [3.27372968e+00]
  [1.95979822e+01]
  [1.67479219e-01]]

 [[4.93080600e+01]
  [6.47669737e-02]
  [7.86568438e+01]
  [4.51913030e+01]
  [9.74478578e-01]]]


In [360]:
# Transpose the latest array
arr21 = arr20.transpose()
print(arr21)

[[[9.21270988e-01 5.31058357e+01 4.93080600e+01]
  [3.00004988e-01 6.59222708e+00 6.47669737e-02]
  [5.07737580e+00 3.27372968e+00 7.86568438e+01]
  [8.33345776e+00 1.95979822e+01 4.51913030e+01]
  [2.93604907e+00 1.67479219e-01 9.74478578e-01]]]


What does the transpose do?

In [361]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr22 = np.random.randint(0, 10, size=(3, 3))
arr23 = np.random.randint(0, 10, size=(3, 2))
print(arr22,arr23)


[[7 2 0]
 [7 2 2]
 [0 4 9]] [[6 9]
 [8 6]
 [8 7]]


In [362]:
# Perform a dot product on the two newest arrays you created
arr24 = np.dot(arr22, arr23)
print(arr24)

[[ 58  75]
 [ 74  89]
 [104  87]]


In [363]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr25 = np.random.randint(0, 10, size=(4, 3))
arr26 = np.random.randint(0, 10, size=(4, 3))
print(arr25,arr26)


[[1 0 6]
 [6 7 4]
 [2 7 5]
 [2 0 2]] [[4 2 0]
 [4 9 6]
 [6 8 9]
 [9 2 6]]


In [364]:
# Perform a dot product on the two newest arrays you created
print(np.dot(arr25, arr26))

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [365]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr25 = arr25.transpose()
print(np.dot(arr25, arr26))

[[ 58  76  66]
 [ 70 119 105]
 [ 88  92  81]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [366]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr27 = np.random.randint(0, 10, size=(4, 4))
arr28 = np.random.randint(0, 10, size=(4, 4))
print(arr27)
print(arr28)

[[0 3 3 4]
 [6 6 3 6]
 [2 5 1 9]
 [8 4 5 3]]
[[9 6 8 6]
 [0 0 8 8]
 [3 8 2 6]
 [5 7 8 4]]


In [367]:
# Compare the two arrays with '>'
comparison_arr = arr27 > arr28
print(comparison_arr)

[[False False False False]
 [ True  True False False]
 [False False False  True]
 [ True False False False]]


What happens when you compare the arrays with `>`?

In [368]:
# Compare the two arrays with '>='
comparison_arr2 = arr27 >= arr28
print(comparison_arr2)

[[False False False False]
 [ True  True False False]
 [False False False  True]
 [ True False False False]]


In [369]:
# Find which elements of the first array are greater than 7
gt7 = np.where(arr27 > 7)
print(arr27[gt7])

[9 8]


In [370]:
# Which parts of each array are equal? (try using '==')
equals = np.where(arr27 == arr28)
print(arr28[equals])


[]


In [371]:
# Sort one of the arrays you just created in ascending order
sorted_arr = np.sort(arr27, axis=None)
print(sorted_arr)


[0 1 2 3 3 3 3 4 4 5 5 6 6 6 8 9]


In [372]:
# Sort the indexes of one of the arrays you just created
sorted_indexes= np.argsort(arr27, axis=None)
print(sorted_indexes)


[ 0 10  8  1  2  6 15  3 13  9 14  4  5  7 12 11]


In [373]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(arr27)
print(max_index)

11


In [374]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(arr27)
print(min_index)


0


In [375]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_index_axis1 = np.argmax(arr27,axis=1)
print(max_index_axis1)

[3 0 3 0]


In [376]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_index_axis1 = np.argmin(arr27,axis=0)
print(min_index_axis1)

[0 0 2 3]


In [377]:
# Create an array of normally distributed random numbers
arr29 = np.random.normal(size=(4,5))
print(arr29)

[[-1.0962658   0.91488432 -0.66606062 -0.51378749  0.3013228 ]
 [-1.45851692 -0.66273831 -0.14647281 -0.84601702 -0.82248937]
 [ 1.08672702  1.00498688 -0.44176602 -0.08416509  1.23701607]
 [-1.42647888  0.33802266  1.9745712   1.96503476 -1.93991122]]


In [378]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr30 = np.linspace(1, 100, num=10)
print(arr30)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.